### ISSUE TITLE
No implementation found for void initEncoder

### ISSUE THREAD

**Issue by JojoRebondy** [B3nedikt/android_lame#1]
Hi and first of all thanks for this wrapper.c example, I was kinda lost regarding how to implement this kind of file for a NDK implementation. 

I'm currently trying to find a new way to decode MP3 in my android app because I've encountered several problems with JLayer. 

So first of all, I've been following the Samsung article you linked in the README file, and I've tried a vast majority of StackOverflow posts regarding this subject, but can't figure what's wrong with my implementation. 

So basically I've been doing everything the article mention to implement libmp3lame into my Android project, but when I try to use the "C" functions listed in the wrapper.c, my application crash with the following log :

> 11-21 09:59:58.461 15450-15450/com.example.jneb.myapplication E/art: No implementation found for void com.example.jneb.myapplication.MainActivity.initEncoder(int, int, int, int, int) (tried Java_com_example_jneb_myapplication_MainActivity_initEncoder and Java_com_example_jneb_myapplication_MainActivity_initEncoder__IIIII)
11-21 09:59:58.461 15450-15450/com.example.jneb.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.jneb.myapplication, PID: 15450
                                                                                java.lang.UnsatisfiedLinkError: No implementation found for void com.example.jneb.myapplication.MainActivity.initEncoder(int, int, int, int, int) (tried Java_com_example_jneb_myapplication_MainActivity_initEncoder and Java_com_example_jneb_myapplication_MainActivity_initEncoder__IIIII)
                                                                                    at com.example.jneb.myapplication.MainActivity.initEncoder(Native Method)
                                                                                    at com.example.jneb.myapplication.MainActivity.onCreate(MainActivity.java:41)
                                                                                    at android.app.Activity.performCreate(Activity.java:6876)

Here is my wrapper.c file:

`#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include <android/log.h>
#include "lame.h"

#define LOG_TAG "LAME ENCODER"
#define LOGD(format, args...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, format, ##args);
#define BUFFER_SIZE 8192
#define be_short(s) ((short) ((unsigned short) (s) << 8) | ((unsigned short) (s) >> 8))

lame_t lame;

int read_samples(FILE *input_file, short *input) {
	int nb_read;
	nb_read = fread(input, 1, sizeof(short), input_file) / sizeof(short);

	int i = 0;
	while (i < nb_read) {
		input[i] = be_short(input[i]);
		i++;
	}

	return nb_read;
}

void Java_com_example_jneb_myapplication_MainActivity_initEncoder(JNIEnv *env,
		jobject jobj, jint in_num_channels, jint in_samplerate, jint in_brate,
		jint in_mode, jint in_quality) {
	lame = lame_init();

//	LOGD("Init parameters:");
	lame_set_num_channels(lame, in_num_channels);
//	LOGD("Number of channels: %d", in_num_channels);
	lame_set_in_samplerate(lame, in_samplerate);
//	LOGD("Sample rate: %d", in_samplerate);
	lame_set_brate(lame, in_brate);
//	LOGD("Bitrate: %d", in_brate);
	lame_set_mode(lame, in_mode);
//	LOGD("Mode: %d", in_mode);
	lame_set_quality(lame, in_quality);
//	LOGD("Quality: %d", in_quality);

	int res = lame_init_params(lame);
//	LOGD("Init returned: %d", res);
}

void Java_com_example_jneb_myapplication_MainActivity_destroyEncoder(
		JNIEnv *env, jobject jobj) {
	int res = lame_close(lame);
//	LOGD("Deinit returned: %d", res);
}

void Java_com_example_jneb_myapplication_MainActivity_encodeFile(JNIEnv *env,
		jobject jobj, jstring in_source_path, jstring in_target_path) {
	const char *source_path, *target_path;
	source_path = (*env)->GetStringUTFChars(env, in_source_path, NULL);
	target_path = (*env)->GetStringUTFChars(env, in_target_path, NULL);

	FILE *input_file, *output_file;
	input_file = fopen(source_path, "rb");
	output_file = fopen(target_path, "wb");

	short input[BUFFER_SIZE];
	char output[BUFFER_SIZE];
	int nb_read = 0;
	int nb_write = 0;
	int nb_total = 0;

//	LOGD("Encoding started");
	while (nb_read = read_samples(input_file, input)) {
		nb_write = lame_encode_buffer(lame, input, input, nb_read, output,
				BUFFER_SIZE);
		fwrite(output, nb_write, 1, output_file);
		nb_total += nb_write;
	}
//	LOGD("Encoded %d bytes", nb_total);

	nb_write = lame_encode_flush(lame, output, BUFFER_SIZE);
	fwrite(output, nb_write, 1, output_file);
//	LOGD("Flushed %d bytes", nb_write);

	fclose(input_file);
	fclose(output_file);
}
`

And here is my Java file calling it : 
`public class MainActivity extends AppCompatActivity {

    private static Context context;
    public static final int NUM_CHANNELS = 1;
    public static final int SAMPLE_RATE = 16000;
    public static final int BITRATE = 128;
    public static final int MODE = 1;
    public static final int QUALITY = 2;
    private WifiHandling wifiHandling;
    private ImageButton play = null;
    private WebSocket mSocket;
    static {
        System.loadLibrary("mp3lame");
    }

    private native void initEncoder(int numChannels, int sampleRate, int bitRate, int mode, int quality);
    private native void destroyEncoder();
    private native int encodeFile(String sourcePath, String targetPath);

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        context = getApplicationContext();
        play = (ImageButton) findViewById(R.id.play_button);
        play.setOnClickListener(mPlayBtnOnClickListener);
        // init WifiHandling
        wifiHandling = new WifiHandling(context);

        initEncoder(NUM_CHANNELS, SAMPLE_RATE, BITRATE, MODE, QUALITY);
    }
`
The problem happens on this last line when I try to call the initEncoder function. Apparently, I have no problem loading the library, and when I initialize the 3 wrapper.c functions they are not highlighted in red so it seems that  android studio know what those functions are refering to. 
Finally in the log, the following line suggest that Android Studio is aware that the function is a native method, but still can't find it :

> at com.example.jneb.myapplication.MainActivity.initEncoder(Native Method)

Obviously there is something wrong about how I implemented libmp3lame, but I can't figure it out. 
Thanks in advance.

**Comment by Glenncito** [comment]
Did you find a solution to this? I am struggling with the same issue now.

**Comment by B3nedikt** [comment]
The issue is due to android not finding the .so file. I made the repository 4 years ago based on a tutorial by Samsung, which is now quite outdated. If you work on an OSS project I would recommend to just use the latest version of android studio which includes C++ support out of the box. No need for old NDK Build like this repo assumes.
See:
https://developer.android.com/ndk/guides/
If you have little experience with C++ its better to use a ready made lib:
https://github.com/naman14/TAndroidLame

I may update this repository with CMake integration if I find the time.
Does this help you?
